language: python
python:
	- "2.7"
	- "3.3"
compiler:
    - g++
notifications:
    email: false
script:
    - cd cpp && ./run_test.sh && cd ..
    - cd python && ./run_test.sh && cd ..
    - echo "Done with cpp and python"
